name: "Editor Recommendations"
description: "The Editor Recommendations Project by the CKEditor Team"

baseurl: "/editor-recommendations"

collections:
  features:
    output: true
  use-cases:
    output: true
  usability:
    output: true

exclude: [ "Gemfile", "README.md" ]

# GitHub defaults.
highlighter: pygments

# GitHub enforced options (non overridable).
safe: true
lsi: false
excerpt_separator: ""

# Enable Github Flavored Markdown.
kramdown:
  input: GFM
